## コンテキストパスを指定
server:
  servlet:
    contextPath: /SmartEC_test2

## データベース接続設定
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartec
#    url: jdbc:postgresql://192.168.56.50:5432/smartec
    username: smartec
    password: 
